name: tennis_app
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  permission_handler: ^11.0.0
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.0.0
  flutter_local_notifications: ^18.0.0
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#def93b"
  adaptive_icon_foreground: "assets/icon.png"

  
flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/tennis.png

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/splash.png # 스플래시 이미지 경로
  android: true
  ios: true
  android_12:
    image: assets/tennis.png