name: tennis_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+11

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  permission_handler: ^11.0.0
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.0.0
  flutter_local_notifications: ^18.0.0
  google_mobile_ads: ^5.2.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  change_app_package_name: ^1.4.0
  android_intent_plus: ^5.2.2
  android_alarm_manager_plus: ^3.0.0
  package_info_plus: ^8.3.0
  provider: ^6.1.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#def93b"
  adaptive_icon_foreground: "assets/icon.png"

  
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/customer.png
    - assets/splash.png

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/splash.png # 스플래시 이미지 경로
  android: true
  ios: true
  android_12:
    image: assets/splash.png