// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihLOyj8Y6MSqkNntV2KCI9ZQIJuMgyRQ',
    appId: '1:151687869137:web:8ee64ab1a1f399ea0a0bf0',
    messagingSenderId: '151687869137',
    projectId: 'tennis-res-app',
    authDomain: 'tennis-res-app.firebaseapp.com',
    storageBucket: 'tennis-res-app.firebasestorage.app',
    measurementId: 'G-LD3Y6V8L3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKHzoZCRMoMDRXKcGdaAMve8uKr0pXfM',
    appId: '1:151687869137:android:2bbc2b77723bea0f0a0bf0',
    messagingSenderId: '151687869137',
    projectId: 'tennis-res-app',
    storageBucket: 'tennis-res-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjJRf2Ng9776GZHQZpIYzojFazd4WxM0',
    appId: '1:151687869137:ios:ea985a4b47c0c2650a0bf0',
    messagingSenderId: '151687869137',
    projectId: 'tennis-res-app',
    storageBucket: 'tennis-res-app.firebasestorage.app',
    iosBundleId: 'com.example.tennisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjJRf2Ng9776GZHQZpIYzojFazd4WxM0',
    appId: '1:151687869137:ios:ea985a4b47c0c2650a0bf0',
    messagingSenderId: '151687869137',
    projectId: 'tennis-res-app',
    storageBucket: 'tennis-res-app.firebasestorage.app',
    iosBundleId: 'com.example.tennisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihLOyj8Y6MSqkNntV2KCI9ZQIJuMgyRQ',
    appId: '1:151687869137:web:dba3984b84bed88d0a0bf0',
    messagingSenderId: '151687869137',
    projectId: 'tennis-res-app',
    authDomain: 'tennis-res-app.firebaseapp.com',
    storageBucket: 'tennis-res-app.firebasestorage.app',
    measurementId: 'G-RQ0JF4LRD3',
  );
}
